# Generated by Django 4.0.3 on 2022-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoogeyBookAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookread',
            name='review',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='bookread',
            name='ISBN',
            field=models.CharField(default='', max_length=20),
        ),
    ]
