# Generated by Django 4.0.3 on 2022-05-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoogeyBookAPP', '0004_bookread_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookread',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
